name: Hugging Face Integration

on:
  push:
    branches:
      - main

jobs:
  run-huggingface:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install transformers torch

    - name: Run Hugging Face script with prompt 1
      run: |
        python your_huggingface_script.py "Explain how generative AI can be used in software development"

    - name: Run Hugging Face script with prompt 2
      run: |
        python your_huggingface_script.py "What are the benefits of using AI in healthcare?"

    - name: Run Hugging Face script with prompt 3
      run: |
        python your_huggingface_script.py "How can AI improve customer service?"
